// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcbdBeuSrUeJeaaD7yZQ4GweNGQZgecKI',
    appId: '1:1069423454147:web:833c7c7de7a4d7d7bdff76',
    messagingSenderId: '1069423454147',
    projectId: 'qurma-app-26675',
    authDomain: 'qurma-app-26675.firebaseapp.com',
    storageBucket: 'qurma-app-26675.appspot.com',
    measurementId: 'G-LX6V4L2VRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfSDJ0JK--h2cXrcenFS99Uz5rlDclq0g',
    appId: '1:1069423454147:android:54f3c5c732ca7959bdff76',
    messagingSenderId: '1069423454147',
    projectId: 'qurma-app-26675',
    storageBucket: 'qurma-app-26675.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy0TxzsrYJtnfZsPXTsJj_9gvLyeNHAPk',
    appId: '1:1069423454147:ios:ee4fb4e550940c78bdff76',
    messagingSenderId: '1069423454147',
    projectId: 'qurma-app-26675',
    storageBucket: 'qurma-app-26675.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy0TxzsrYJtnfZsPXTsJj_9gvLyeNHAPk',
    appId: '1:1069423454147:ios:ee4fb4e550940c78bdff76',
    messagingSenderId: '1069423454147',
    projectId: 'qurma-app-26675',
    storageBucket: 'qurma-app-26675.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcbdBeuSrUeJeaaD7yZQ4GweNGQZgecKI',
    appId: '1:1069423454147:web:0fff294697d3910fbdff76',
    messagingSenderId: '1069423454147',
    projectId: 'qurma-app-26675',
    authDomain: 'qurma-app-26675.firebaseapp.com',
    storageBucket: 'qurma-app-26675.appspot.com',
    measurementId: 'G-B7SRCEZE9H',
  );
}
